[package]
name = "bitwheel"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"

[dev-dependencies]
criterion = "0.8.1"
hdrhistogram = "7.5.4"


[[bench]]
name = "bitwheel"
harness = false
